version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/home/node/app/
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: app
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev